api/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken import views
from knox import views as knox_views
from api.views import LoginView, CreateUserAPI, EmpView, UserViewSet


router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'emp', EmpView)


urlpatterns = [
    path('', include(router.urls)),
    path('token-auth/', views.obtain_auth_token),
    # path('auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('auth/', include('knox.urls')),
    path('login/', LoginView.as_view(), name='knox_login'),
    path('logout/', knox_views.LogoutView.as_view(), name='knox_logout'),
    path('logoutall/', knox_views.LogoutAllView.as_view(), name='knox_logoutall'),
    path('register/', CreateUserAPI.as_view(), name='knox_register'),
    
]

ubook_lms/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('api/', include('api.urls')),
    path('accounts/', include('accounts.urls')),
    path('department/', include('departments.urls')),
    path('adminstration/', include('adminstartion.urls')),

]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.utils.timezone import now


class User(AbstractUser):
    gender = models.SmallIntegerField(choices=((0,'None'), (1,'Mmale'), (2,'Female'), (3,'Trans')), default=0) 
    adhar = models.IntegerField(blank=True, null=True, unique=True)
    dob = models.DateField(blank=True, null=True, )
    father_name = models.CharField(max_length=256, blank=True,null=True )
    mother_name = models.CharField(max_length=256, blank=True, null=True)
    type = models.IntegerField(choices=((0,'None'), (1,'Student'), (2,'Staff'), (3,'lower_staf')), default=0)
  


class Student(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, limit_choices_to={'type':1}, )
    contact_number = models.IntegerField(null=True,blank=True)
    addr = models.TextField(blank=True, default='Home')
    email = models.CharField(max_length=256,blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.user)


EMPLOYEMENT = [(0,'None'),(1,'PRINCIPLE'),(2,'HOD'),(2,'PROFESSOR'),(3,'ASST-PROFESSOR'),(4,'ASSOCIAT-PROFESSOR'),(5,'LAB-INCHARGE'),(6,'LAB-ASSISTANT'),]
PROJECT_STATUS = [(0,'None'),(1,'DEV'),(2,'PROD'),(3,'LIVE'),(4,'CLOSED')]


class Projects(models.Model):
    pr_id = models.CharField(max_length=256, unique=True)
    pr_name = models.CharField(max_length=256)
    client = models.CharField(max_length=256)
    start = models.DateField(auto_now_add=True)
    end = models.DateField(null=True,blank=True)
    status = models.SmallIntegerField(choices=PROJECT_STATUS, default=0)

    def __str__(self):
        return self.pr_id


class JobHistory(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'type':2}, )
    designation = models.SmallIntegerField(choices=EMPLOYEMENT, default=0)
    start = models.DateField(auto_now_add=True)
    end = models.DateField(null=True,blank=True)

    def __str__(self):
        return str(self.project)





    
            







# class YearInSchool(models.Model):
#     pass

# @receiver(post_save, sender=User)
# def create_student(sender, instance, created, **kwargs):
#     if created:
#         Student.objects.create(user=instance)
    

# @receiver(post_save, sender=User)
# def save_student(sender, instance, **kwargs):
#     instance.student.save()

templates/access_denied.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UBOOK| Access denaied</title>

    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ae46928e6f.js" crossorigin="anonymous"></script>
</head>
<div class="h-screen w-screen bg-black flex flex-col justify-center items-center ">
    <i class="fas fa-dragon text-9xl text-red-900 px-6 py-6"></i>
    <a href='/' class="font-mono text-white text-5xl">Access denied</a>
    {{reason}}
</div>

<body>




</body>

</html>

templates/add_student.html
{% extends 'index.html' %} {% block add_student_form %} {% comment %}
<div class="min-h-screen pt-1 font-mono my-8">
    <div class="container mx-auto">
        <div class="inputs w-full max-w-2xl mx-auto">
            <h2 class="text-2xl text-gray-900">Student details:</h2>

            <form method="POST" action="/administration/create-student/" class="mt-6 border-t border-gray-400 pt-4 pb-4">
                {% csrf_token %}
                <div class='flex flex-wrap -mx-3 mb-6'>
                    <div class="personal w-full pt-4">
                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>first name</label>
                                <input name='first_name' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' placeholder="First Name">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>last name</label>
                                <input name='last_name' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' placeholder="Second Name">
                            </div>
                        </div>

                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Adhar Number</label>
                            <input name='adhar' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' placeholder="1234-5678-9012" type='number'>
                        </div>

                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>date of birth</label>
                            <input name='dob' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='date'>
                        </div>

                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Father Name</label>
                                <input name='father' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' placeholder="Father name">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Mother Name</label>
                                <input name='mother' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' placeholder="Mother name">
                            </div>
                        </div>
                        <div class="border-b border-geen-300"></div>

                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Class</label>
                                <input name='class' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='number' placeholder="Class ...">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Section</label>
                                <input name='section' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' placeholder="Section ..">
                            </div>
                        </div>
                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>fav language</label>
                            <div class="flex-shrink w-full inline-block relative">
                                <select name='lang' class="block appearance-none text-gray-600 w-full bg-white border border-gray-400 shadow-inner px-4 py-2 pr-8 rounded">
                                    <option>English</option>
                                    <option>Telugu</option>
                                    <option>Hindi</option>
                                </select>
                                <div class="pointer-events-none absolute top-0 mt-3  right-0 flex items-center px-2 text-gray-600">
                                    <i class="fas fa-caret-down"></i>
                                </div>
                            </div>
                        </div>
                        <div class="border-b border-red-200 m-2"></div>

                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Contact Number</label>
                            <input name='phone' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='tel'>
                        </div>
                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Address</label>
                            <textarea name='address' class='bg-gray-100 rounded-md border leading-normal resize-none w-full h-20 py-2 px-3 shadow-inner border border-gray-400 font-medium placeholder-gray-700 focus:outline-none focus:bg-white'></textarea>
                        </div>
                    </div>
                    <div class='w-full md:w-full px-3 mb-6'>
                        <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' for='grid-text-1'>email address</label>
                        <input name='email' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' id='grid-text-1' type='text' placeholder='Enter email'>
                    </div>



                    <div class="flex justify-end w-full">
                        <button class="appearance-none bg-gray-200 text-gray-900 px-2 py-1 shadow-sm border border-gray-400 rounded-md mr-3" type="submit">save changes</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div> {% endcomment %}

<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">
    submit
</button>
</form>
{% endblock add_student_form %}

templates/attendence.html
{% extends 'index.html' %}

{% block attendence %}
<style>
.toggle__dot {
  top: -.25rem;
  left: -.25rem;
  transition: all 0.2s ease-in-out;
}

input:checked ~ .toggle__dot {
  transform: translateX(100%);
  background-color: #03fc03;
}
</style>

<script>
function toggle(tid) {
  var x = document.getElementById(arguments[0]);
  
  if (x.value === "a") {
    x.value = "p";
    console.log(1)
  } else {
    x.value = "a";
    console.log(0)
  }
}
</script>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="flex flex-col m-1 lg:m-4">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-4">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 rounded-md">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50  text-xs">
            <tr>
              <th scope="col" class="p-2 text-center  font-medium text-green-500 uppercase tracking-wider">
                Roll No.
              </th>
              <th scope="col" class="p-2 text-center  font-medium text-green-500 uppercase tracking-wider">
                UID
              </th>
              <th scope="col" class="p-2 text-center font-medium text-green-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" class="p-2 text-center font-medium text-green-500 uppercase tracking-wider">
                Attendence
              </th>
              
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200 ">
            {%for student in students%}
            <tr>
              <td class="p-2 whitespace-nowrap text-center font-medium text-sm text-gray-500">{{forloop.counter}}</td>
              <td class="p-2 whitespace-nowrap text-center font-medium text-sm text-gray-500">{{student.username}}</td>
              <td class="p-2 whitespace-nowrap text-center font-medium text-sm text-gray-500">{{student.first_name}}</td>
              <td class="p-2 whitespace-nowrap flex items-center justify-center text-sm font-medium" >
                  <label for="t{{forloop.counter}}" class="flex items-center cursor-pointer")>
                    <!-- toggle -->
                    <div class="relative">
                      <!-- input -->
                      <input id="t{{forloop.counter}}" type="checkbox" class="hidden" value="a">
                      <!-- line -->
                      <div class="toggle__line w-10 h-4 bg-gray-400 rounded-full shadow-inner" onclick=toggle('t{{forloop.counter}}')></div>
                      <!-- dot -->
                      <div class="toggle__dot absolute w-6 h-6 bg-red-400 rounded-full shadow inset-y-0 left-0" onclick=toggle('t{{forloop.counter}}')></div>
                    </div>
                  </label>
              </td>
            </tr>
            {%endfor%}

            <!-- More items... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>






{% endblock attendence %}

templates/dashboard.html
{% extends 'index.html' %}

{% block dashboard %}
<div class="p-2">
    <div class="p-2 flex justify-center">
        <div class="w-full overflow-x-auto mx-auto py-2 sm:px-2 lg:px-8">
            <div class="flex flex-row space-x-1 ">

                <div class="w-full lg:w-1/5">
                    <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-purple-400">
                        <div class="flex items-center space-x-4">
                            <i class="fas fa-user-check lg:text-2xl"></i>
                            <div class="flex flex-col">
                                <div class="text-lg">50</div>
                                <div class="text-sm text-gray-400">Teachers</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="w-full lg:w-1/5">
                    <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-blue-400">
                        <div class="flex items-center space-x-4">
                            <i class="fas fa-users text-2xl sm:text-l"></i>
                            <div class="flex flex-col justify-center">
                                <div class="text-lg">3456</div>
                                <div class="text-sm text-gray-400">Students</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="w-full lg:w-1/5">
                    <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-yellow-400">
                        <div class="flex items-center">
                            <div class="icon w-14 p-3.5 bg-yellow-400 text-white rounded-full mr-3">
                                <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" />
                        </svg>
                            </div>
                            <div class="flex flex-col justify-center">
                                <div class="text-lg">3456</div>
                                <div class="text-sm text-gray-400">Products</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="w-full lg:w-1/5">
                    <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-red-400">
                        <div class="flex items-center">
                            <div class="icon w-14 p-3.5 bg-red-400 text-white rounded-full mr-3">
                                <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
                        </svg>
                            </div>
                            <div class="flex flex-col justify-center">
                                <div class="text-lg">12658</div>
                                <div class="text-sm text-gray-400">Orders</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="w-full lg:w-1/5">
                    <div class="widget w-full p-4 rounded-lg bg-white border-l-4 border-green-400">
                        <div class="flex items-center">
                            <div class="icon w-14 p-3.5 bg-green-400 text-white rounded-full mr-3">
                                <svg fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                            </div>
                            <div class="flex flex-col justify-center">
                                <div class="text-lg">$948'560</div>
                                <div class="text-sm text-gray-400">Revenue</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock dashboard %}

templates/edit_student.html
{% extends 'index.html' %} {% block change_student_form %}
<!-- <div class="min-h-screen pt-1 font-mono my-8">
    <div class="container mx-auto">
        <div class="inputs w-full max-w-2xl mx-auto">
            <h2 class="text-2xl text-gray-900">Student details:</h2>

            <form method="POST" action="/{{object}}/student/" class="mt-6 border-t border-gray-400 pt-4 pb-4">
                {% csrf_token %}
                <input name="user" required id="id_user" value="{{object}}">
                <div class='flex flex-wrap -mx-3 mb-6'>
                    <div class="personal w-full pt-4">
                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>first name</label>
                                <input name="first_name" class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{form.first_name.value}}" placeholder="first name">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>last name</label>
                                <input name="last_name" class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{form.last_name.value}}" placeholder="Second Name">
                            </div>
                        </div>

                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Adhar Number</label>
                            <input name="adhar" class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' placeholder="1234-5678-9012" value="{{form.adhar.value}}"
                                type='number'>
                        </div>
                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>date of birth</label>
                                <input name='dob' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='date' value="{{form.birth.value|date:' Y-m-d '}}">
                            </div>


                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>gender</label>
                                <div class="flex-shrink w-full inline-block relative">
                                    <select name='lang' class="block appearance-none text-gray-600 w-full bg-white border border-gray-400 shadow-inner px-4 py-3 pr-8 rounded">
                                        <option>{{form.gender.value}}</option>
                                        <option>Male</option>
                                        <option>Female</option>
                                        <option>Trans</option>
                                    </select>
                                    <div class="pointer-events-none absolute top-0 mt-3  right-0 flex items-center px-2 text-gray-600">
                                        <i class="fas fa-caret-down"></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Father Name</label>
                                <input name='father_name' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{form.father_name.value}}">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Mother Name</label>
                                <input name='mother_name' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{form.mother_name.value}}">
                            </div>
                        </div>
                        <div class="border-b border-geen-300"></div>

                        <div class="flex items-center justify-between mt-4">
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Class</label>
                                <input name='class' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='number' min="1" max="10" value="{{form.student_class.value}}"
                                    placeholder="Class ...">
                            </div>
                            <div class='w-full md:w-1/2 px-3 mb-6'>
                                <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Section</label>
                                <input name='section' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' type='text' value="{{form.student_section.value}}" placeholder="Section ..">
                            </div>
                        </div>
                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>fav language</label>
                            <div class="flex-shrink w-full inline-block relative">
                                <select name='lang' class="block appearance-none text-gray-600 w-full bg-white border border-gray-400 shadow-inner px-4 py-2 pr-8 rounded">
                                    <option value="English" >{{form.fav_language.value}}</option>
                                    <option value='1'>English</option>
                                    <option value='2'>Telugu</option>
                                    <option value='3'>Hindi</option>
                                </select>
                                <div class="pointer-events-none absolute top-0 mt-3  right-0 flex items-center px-2 text-gray-600">
                                    <i class="fas fa-caret-down"></i>
                                </div>
                            </div>
                        </div>
                        <div class="border-b border-red-200 m-2"></div>

                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Contact Number</label>
                            <input name='phone' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' value="{{form.contact_number.value}}" type='tel'>
                        </div>
                        <div class='w-full md:w-full px-3 mb-6'>
                            <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2'>Address</label>
                            <textarea name='address' class='bg-gray-100 rounded-md border leading-normal resize-none w-full h-20 py-2 px-3 shadow-inner border border-gray-400 font-medium placeholder-gray-700 focus:outline-none focus:bg-white'>{{form.addr.value}}</textarea>
                        </div>
                    </div>
                    <div class='w-full md:w-full px-3 mb-6'>
                        <label class='block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' for='grid-text-1'>email address</label>
                        <input name='email' class='appearance-none block w-full bg-white text-gray-700 border border-gray-400 shadow-inner rounded-md py-3 px-4 leading-tight focus:outline-none  focus:border-gray-500' id='grid-text-1' type='text' value="{{form.email.value}}"
                            placeholder='Enter email'>
                    </div>



                    <div class="flex justify-end w-full">
                        <button class="appearance-none bg-gray-200 text-gray-900 px-2 py-1 shadow-sm border border-gray-400 rounded-md mr-3" type="submit">save changes</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div> -->
<form action="/{{object}}/student/" method="post">
    {{object}} {% csrf_token %} {{form.as_p}}
    <button type="submit">UPDATE</button>
</form>



{% endblock change_student_form %}

templates/sample.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ae46928e6f.js" crossorigin="anonymous"></script>

</head>

<body>
    {{userid}}
    {{password}}
    {{occupancy}}
</body>

</html>

templates/sample2.html
<!DOCTYPE html>{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>{{object}}</h1>
    <form  method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Update</button>
    </form>
</body>


</html>